name: my_app
description: A Flutter project

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ^3.19.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  lottie: ^3.3.1
  flutter_spinkit: ^5.2.1
  animations: ^2.0.11
  shared_preferences: ^2.5.3
  flutter_markdown: ^0.6.10
  http: ^1.1.0


flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter