name: CI/CD Pipeline - Registry-Free

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # env:
    #   GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    #   DSN: ${{ secrets.DSN }}

    steps:
      - uses: actions/checkout@v3
      
      # Optional: Run tests before deployment
      # - name: Run Backend Tests
      #   run: |
      #     cd backend
      #     go test ./...
      
      # - name: Run Frontend Tests
      #   run: |
      #     cd frontend
      #     flutter test
      
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/demonit/first-aid-helper
            git pull origin main
            export GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}"
            docker compose up -d --build
